config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :promotions, only: %i[index new create show edit update] do
    post 'approve', on: :member, to: 'promotions#approve'
    post 'generate_coupons', on: :member, to: 'promotions#generate_coupons'
    resources :coupons, only: :show do
      post 'discard', on: :member, to: 'coupons#discard'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/burnt_coupon.rb
class BurntCoupon < ApplicationRecord
  belongs_to :coupon
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :promotion
  enum status: { available: 0, burnt: 5, discarded: 10 }

  has_one :burnt_coupon, dependent: :destroy
end

app/models/product.rb
class Product
  attr_accessor :id, :key

  class << self
    def host
      Rails.configuration.apis_servers[:product_url]
    end

    def api_version
      'v1'
    end

    def product_url
      url = "#{host}/api/#{api_version}/product_types"
      response = Faraday.get(url)
      JSON.parse(response.body, symbolize_names: true)
    end

    def all
      products = product_url

      products.map do |product|
        Product.new(id: product[:id], key: product[:product_key])
      end
    end

    def find(id)
      all.detect { |product| product.id == id}
    end
  end

  def initialize(id:, key:)
    self.id = id
    self.key = key
  end
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  belongs_to :user
  has_many :coupons, dependent: :destroy
  enum status: { waiting_for_approval: 0, approved: 1, issued: 2 }
  validates :description, :prefix, :discount_percentage,
            :max_discount_value, :start_date, :end_date,
            :max_usage, presence: true
  validates :prefix, length: { maximum: 6 }
  validates :discount_percentage, :max_discount_value, 
             numericality: { greater_than: 0, 
                             less_than_or_equal_to: 100 }

  validate :start_date_in_present_or_future?
  validate :end_date_greater_than_start_date?

  def generate_coupons
    max_usage.times do |n|
      code = prefix + (n + 1).to_s.rjust(4, '0')
      coupons.create!(code: code)
    end
  end

  private

  def start_date_in_present_or_future?
    return true if start_date.present? && start_date >= Date.today
    add_custom_error(attribute: :start_date, 
                     message: I18n.t(:start_date_in_past, scope: :validate))
    false
  end

  def end_date_greater_than_start_date?
    return true if end_date.present? && end_date > start_date
    add_custom_error(attribute: :end_date,
                     message: I18n.t(:end_dt_smaller_than_start_dt, 
                                     scope: :validate))
    false  
  end

  def add_custom_error(attribute:, message:)
    errors.add(attribute, message)
  end
end

app/models/types.rb
module Types
  include Dry.Types()
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  def show
    @promotion = Promotion.find(find_params.fetch(:promotion_id))
    @coupon = Coupon.find(find_params.fetch(:id))
  end
  def discard; end

  private

  def find_params
    params.permit(:promotion_id, :id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :all_promotions, only: :index
  before_action :all_products, only: %i[index create edit update]

  def index
    @promotion = Promotion.new
  end

  def create
    @promotion = Promotion.new(promotion_params)
    fill_promotion_fields
    return redirect_to promotions_path, notice: t('.success') \
           if @promotion.save
    
    flash.now[:alert] = t('.error')
    render :index
  end
  
  def edit
    @promotion = Promotion.find(find_promotion.fetch(:id))
  end

  def update
    @promotion = Promotion.find(find_promotion.fetch(:id))
    return redirect_to promotions_path, notice: t('.success') \
           if @promotion.update(promotion_params)
    
    flash.now[:alert] = t('.error')
    render :edit
  end

  def show
    @promotion = Promotion.find(find_promotion.fetch(:id))
    @cupons = @promotion.coupons.where(status: :available)
  end

  def approve
    promotion = Promotion.find(find_promotion.fetch(:id))
    promotion.approved!
    redirect_back fallback_location: promotion_path, 
                  notice: t('.approved')
  end

  def generate_coupons
    @promotion = Promotion.find(find_promotion.fetch(:id))
    if @promotion.approved?
      @promotion.issued!
      @promotion.generate_coupons
      redirect_back fallback_location: promotion_path,
                    notice: @promotion.max_usage.to_s + " " +
                            t('.created_cupons')
    else
      redirect_back fallback_location: promotion_path,
                    alert: t('.not_approved')
    end
  end


  private

  def all_promotions
    @promotions = Promotion.all
  end

  def promotion_params
    params.require(:promotion).permit(:description, :prefix,
      :discount_percentage, :max_discount_value, :start_date,
      :end_date, :max_usage, :product_id)
  end

  def find_promotion
    params.permit(:id)
  end

  def all_products
    @products = Product::Client.all
  end

  def fill_promotion_fields
    @promotion.user = current_user
    product = Product::Client.find(@promotion.product_id.to_i)
    @promotion.product_key = product.key
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coupons/show.html.erb
<h1 class="ls-title-intro ls-ico-text2">
  <%= Coupon.model_name.human %>
</h1>

<div class="ls-alert-danger"><%= alert %></div>
<div class="ls-alert-success"><%= notice %></div>

<div class="ls-list">
  <header class="ls-list-header">
    <div class="ls-list-title col-md-9">
      <a href="#" >
        <%= @coupon.code %>
      </a>
      <small><%= @promotion.description %></small>
    </div>
    <div class="col-md-3 ls-txt-right">
      <%= link_to t('.discard_button'), discard_promotion_coupon_path(@coupon), 
                  class: 'ls-btn-primary-danger', method: :post %>
    </div>
  </header>
  
  <div class="ls-list-content ">
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Coupon.human_attribute_name('status') %>
      </span>
      <strong>
        <%= @coupon.status %>
      </strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Coupon.human_attribute_name('created_at') %>
      </span>
      <strong>
        <%= @coupon.created_at.strftime('%d/%m/%Y') %>
      </strong>
    </div>
  </div>
</div>

app/views/home/index.html.erb
 <h1 class="ls-title-intro ls-ico-home">Página inicial</h1>
 <p>Bem vindo a Gestão Cupons</p>

app/views/layouts/_app.html.erb
<div class="ls-topbar ">

<!-- Barra de Notificações -->
<div class="ls-notification-topbar">

<!-- Dropdown com detalhes da conta de usuário -->
<div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
  <a href="#" class="ls-ico-user">
    <span class="ls-name"><%= current_user.email %></span>
  </a>

  <nav class="ls-dropdown-nav ls-user-menu">
    <ul>
      <li><%= link_to t('.logout_button'), destroy_user_session_path, method: :delete %></li>
    </ul>
  </nav>
</div>
</div>

<span class="ls-show-sidebar ls-ico-menu"></span>

<a href="/locawebstyle/documentacao/exemplos//pre-painel"  class="ls-go-next"><span class="ls-text">Voltar à lista de serviços</span></a>

<!-- Nome do produto/marca com sidebar -->
<h1 class="ls-brand-name">
  <a href="home" class="ls-ico-earth">
    <small>Uma descrição ou outro nome</small>
    O nome do Produto
  </a>
</h1>

<!-- Nome do produto/marca sem sidebar quando for o pre-painel  -->
</div>


<aside class="ls-sidebar">

<div class="ls-sidebar-inner">
  <a href="/locawebstyle/documentacao/exemplos//pre-painel"  class="ls-go-prev"><span class="ls-text">Voltar à lista de serviços</span></a>

  <nav class="ls-menu">
    <ul>
      <li><%= link_to Promotion.model_name.human(count: 2), promotions_path, class: 'ls-ico-bell-o' %></li>
  
    </ul>
  </nav>


</div>
</aside>


<main class="ls-main">
  <div class="container-fluid">

    <%= yield %>

  </div>
</main>

<aside class="ls-notification">
  <nav class="ls-notification-list" id="ls-notification-curtain" style="left: 1716px;">
    <h3 class="ls-title-2">Notificações</h3>
    <ul>
      <li class="ls-dismissable">
        <a href="#">Blanditiis est est dolorem iure voluptatem eos deleniti repellat et laborum consequatur</a>
        <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
      </li>
      <li class="ls-dismissable">
        <a href="#">Similique eos rerum perferendis voluptatibus</a>
        <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
      </li>
      <li class="ls-dismissable">
        <a href="#">Qui numquam iusto suscipit nisi qui unde</a>
        <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
      </li>
      <li class="ls-dismissable">
        <a href="#">Nisi aut assumenda dignissimos qui ea in deserunt quo deleniti dolorum quo et consequatur</a>
        <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
      </li>
      <li class="ls-dismissable">
        <a href="#">Sunt consequuntur aut aut a molestiae veritatis assumenda voluptas nam placeat eius ad</a>
        <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
      </li>
    </ul>
  </nav>

  <nav class="ls-notification-list" id="ls-help-curtain" style="left: 1756px;">
    <h3 class="ls-title-2">Feedback</h3>
    <ul>
      <li><a href="#">&gt; quo fugiat facilis nulla perspiciatis consequatur</a></li>
      <li><a href="#">&gt; enim et labore repellat enim debitis</a></li>
    </ul>
  </nav>

  <nav class="ls-notification-list" id="ls-feedback-curtain" style="left: 1796px;">
    <h3 class="ls-title-2">Ajuda</h3>
    <ul>
      <li class="ls-txt-center hidden-xs">
        <a href="#" class="ls-btn-dark ls-btn-tour">Fazer um Tour</a>
      </li>
      <li><a href="#">&gt; Guia</a></li>
      <li><a href="#">&gt; Wiki</a></li>
    </ul>
  </nav>
</aside>

app/views/layouts/_sign.html.erb
<div class="ls-login-parent">
  <div class="ls-login-inner">
    <div class="ls-login-container">
      <div class="ls-login-box">
        <h1 class="ls-login-logo"><%= image_tag "logo-locaweb.png" %></h1>
        <div class="ls-alert-danger"><%= alert %></div>
        <div class="ls-alert-success"><%= notice %></div>
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="ls-theme-light-blue">
  <head>
    <title>Coupon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- LOCASTYLE -->
    <meta charset="utf-8">
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="description" content="Insira aqui a descrição da página.">
  </head>

  <body>
    <%= render 'layouts/app' if user_signed_in? %>
    <%= render 'layouts/sign' unless user_signed_in? %>
  </body>
</html>

app/views/promotions/_form.html.erb
<%= form_with model: @promotion, local: true, 
              class: 'ls-form ls-form-horizontal' do | form |%>
  <div class="ls-modal-body" id="myModalBody">
    <fieldset>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :description %>
        <%= form.text_field :description %>
      </label>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :prefix %>
        <%= form.text_field :prefix %>
      </label>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :discount_percentage %>
        <%= form.number_field :discount_percentage, in: 1.0..100.0, step: 0.01 %>
      </label>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :max_discount_value %>
        <%= form.text_field :max_discount_value, in: 1.0..100.0, step: 0.01 %>
      </label>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :start_date %>
        <%= form.date_field :start_date %>
      </label>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :end_date %>
        <%= form.date_field :end_date %>
      </label>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :max_usage %>
        <%= form.number_field :max_usage %>
      </label>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :product_id, t('.label_product') %>
        <%= form.collection_select :product_id, @products, :id, :key %>
      </label>
    </fieldset> 
  </div>
  <div class="ls-modal-footer">
    <%= form.submit class: 'ls-btn-primary' %>
  </div>
<% end %>

app/views/promotions/_modal.html.erb
<div class="ls-modal" id="addPromotion">
  <div class="ls-modal-box">
    <div class="ls-modal-header">
      <button data-dismiss="modal">&times;</button>
      <h4 class="ls-modal-title"><%= t('.title') %></h4>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/promotions/edit.html.erb
 <h1 class="ls-title-intro ls-ico-bell-o">
  <%= Promotion.model_name.human(count: 1) %>
</h1>

<div class="ls-alert-danger"><%= alert %></div>
<div class="ls-alert-success"><%= notice %></div>

<% if @promotion.errors.any? %>
<ul style="list-style-type:none">
  <h4><%= t('.errors_phrase') %>: </h4><br>
  <% @promotion.errors.full_messages.each do |msg| %>
    <li>- <%= msg %></li>
  <% end %>
</ul>
 <br><br>
 <% end %>

<%= render 'form' %>

app/views/promotions/index.html.erb
<h1 class="ls-title-intro ls-ico-bell-o">
  <%= Promotion.model_name.human(count: 2) %>
</h1>

<div class="ls-alert-danger"><%= alert %></div>
<div class="ls-alert-success"><%= notice %></div>

<% if @promotion.errors.any? %>
<ul style="list-style-type:none">
  <h4><%= t('.errors_phrase') %>: </h4><br>
  <% @promotion.errors.full_messages.each do |msg| %>
    <li>- <%= msg %></li>
  <% end %>
</ul>
 <br><br>
 <% end %>

<button data-ls-module="modal" data-target="#addPromotion" 
        class="ls-btn-primary ls-ico-plus"> <%= t('.add_button') %>
</button>

 <table class="ls-table ls-table-striped">
  <thead>
    <tr>
      <th class="hidden-xs">
        <%= Promotion.human_attribute_name('id') %>
      </th>
      <th>
        <%= Promotion.human_attribute_name('product_key') %>
      </th>
      <th class="hidden-xs">
        <%= Promotion.human_attribute_name('prefix') %>
      </th>
      <th>
        <%= Promotion.human_attribute_name('discount_percentage') %>
      </th>
      <th class="hidden-xs">
        <%= Promotion.human_attribute_name('status') %>
      </th>
    
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @promotions.each do | promotion | %>
    <tr id=<%= "promotion-#{promotion.id}" %>>
      <td class="hidden-xs">
        <%= link_to promotion.id, promotion %>
      </td>
      <td>
        <%= promotion.product_key %>
      </td>
      <td class="hidden-xs">
        <%= promotion.prefix %>
      </td>
      <td>
        <%= format("%.0f", promotion.discount_percentage) %>%
      </td>
      <td class="hidden-xs">
        <%= promotion.status %>
      </td>
      <td>
        <% if promotion.waiting_for_approval? || promotion.approved? %>
          <%= link_to t('.edit_button'), edit_promotion_path(promotion), class: 'ls-btn' %>
        <% else %>
          <%= link_to t('.edit_button'), edit_promotion_path(promotion), class: 'ls-btn',
                                         disabled: :true %>
        <% end %>
         
        <!-- <%= link_to '', promotion, method: :delete, class: 'ls-btn-primary-danger ls-ico-remove',
                                     data: { confirm: t('.confirmation_deletion') }, 
                                     id: 'deletar_button' %> -->
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= render 'modal' %>

<br><br>

app/views/promotions/show.html.erb
<h1 class="ls-title-intro ls-ico-bell-o">
  <%= Promotion.model_name.human %>
</h1>

<div class="ls-alert-danger"><%= alert %></div>
<div class="ls-alert-success"><%= notice %></div>

<div class="ls-list">
  <header class="ls-list-header">
    <div class="ls-list-title col-md-9">
      <a href="#" >
        <%= @promotion.description %>
      </a>
      <small><%= @promotion.prefix %></small>
    </div>
    <div class="ls-group-btn ls-group-active">
      <% if @promotion.waiting_for_approval? %>
        <%= link_to t('.approved_button'), approve_promotion_path(@promotion), 
                    class: 'ls-btn-primary', method: :post %>
      <% else %>
        <%= link_to t('.approved_button'), approve_promotion_path(@promotion), 
                    class: 'ls-btn-primary', method: :post, disabled: :true %>
      <% end %>

      <% if @promotion.approved? %>
        <%= link_to t('.generate_coupons'), generate_coupons_promotion_path(@promotion), 
                    class: 'ls-btn-primary', method: :post %>
      <% else %>
        <%= link_to t('.generate_coupons'), generate_coupons_promotion_path(@promotion), 
                    class: 'ls-btn-primary', method: :post, disabled: :true %>
      <% end %>
    </div>
  </header>
  
  <div class="ls-list-content ">
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Promotion.human_attribute_name('discount_percentage') %>
      </span>
      <strong>
        <%= format("%.0f", @promotion.discount_percentage) %>%
      </strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Promotion.human_attribute_name('max_discount_value') %>
      </span>
      <strong>
        <%= format("%.0f", @promotion.max_discount_value) %>%
      </strong>
    </div>
  </div>
  <div class="ls-list-content ">
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Promotion.human_attribute_name('start_date') %>
      </span>
      <strong>
        <%= @promotion.start_date.strftime('%d/%m/%Y') %>
      </strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Promotion.human_attribute_name('end_date') %>
      </span>
      <strong>
        <%= @promotion.end_date.strftime('%d/%m/%Y') %>
      </strong>
    </div>
  </div>
  <div class="ls-list-content ">
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Promotion.human_attribute_name('max_usage') %>
      </span>
      <strong>
        <%= @promotion.max_usage %>
      </strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Promotion.human_attribute_name('status') %>
      </span>
      <strong>
        <%= @promotion.status %>
      </strong>
    </div>
  </div>
  <div class="ls-list-content ">
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Promotion.human_attribute_name('user') %>
      </span>
      <strong>
        <%= @promotion.user.email %>
      </strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Promotion.human_attribute_name('product_key') %>
      </span>
      <strong>
        <%= @promotion.product_key %>
      </strong>
    </div>
  </div>
</div>

<% unless @cupons.empty? %>
  <div class="ls-list">
    <header class="ls-list-header">
      <div class="ls-list-title col-md-9">
        <a href="#" ><%= t('.coupons_title') %></a>
      </div>
      <div class="col-md-12">
        <% @cupons.each do |coupom| %>
          <% if coupom.available? %>
            <% btn = 'ls-btn-primary' %>
          <% elsif coupom.burnt? %>
            <% btn = 'ls-btn-danger' %>
          <% else %>
            <% btn = 'ls-btn-dark' %>
          <% end %>
          <%= link_to coupom.code, promotion_coupon_path(@promotion, coupom), class: btn %>
        <% end %>
      </div>
    </header>
  </div>
<% end %>